# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1963, 1060)
        self.bg_1 = QtWidgets.QLabel(Form)
        self.bg_1.setGeometry(QtCore.QRect(-190, -30, 2231, 1061))
        self.bg_1.setText("")
        self.bg_1.setPixmap(QtGui.QPixmap("../../Pictures/2510353.png"))
        self.bg_1.setScaledContents(True)
        self.bg_1.setObjectName("bg_1")
        self.bg_2 = QtWidgets.QLabel(Form)
        self.bg_2.setGeometry(QtCore.QRect(730, 450, 391, 101))
        self.bg_2.setStyleSheet("\n"
"background-color: rgb(236, 0, 0);")
        self.bg_2.setText("")
        self.bg_2.setObjectName("bg_2")
        self.bg_3 = QtWidgets.QLabel(Form)
        self.bg_3.setGeometry(QtCore.QRect(890, 380, 71, 181))
        self.bg_3.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bg_3.setText("")
        self.bg_3.setObjectName("bg_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(840, 230, 161, 151))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Downloads/logo.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.studyasot = QtWidgets.QTextBrowser(Form)
        self.studyasot.setGeometry(QtCore.QRect(745, 460, 361, 81))
        self.studyasot.setObjectName("studyasot")
        self.startbutton = QtWidgets.QPushButton(Form)
        self.startbutton.setGeometry(QtCore.QRect(500, 470, 241, 61))
        self.startbutton.setStyleSheet("\n"
"background-color: rgb(255, 77, 23);\n"
"")
        self.startbutton.setObjectName("startbutton")
        self.stopbutton = QtWidgets.QPushButton(Form)
        self.stopbutton.setGeometry(QtCore.QRect(1120, 460, 231, 71))
        self.stopbutton.setStyleSheet("background-color: rgb(255, 68, 55);")
        self.stopbutton.setObjectName("stopbutton")
        self.bg_1.raise_()
        self.startbutton.raise_()
        self.bg_2.raise_()
        self.bg_3.raise_()
        self.label.raise_()
        self.studyasot.raise_()
        self.stopbutton.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.startbutton.setText(_translate("Form", "start"))
        self.stopbutton.setText(_translate("Form", "stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
